apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-reverse-proxy
  name: nginx-reverse-proxy
  namespace: myapps
spec:
  ports:
    - name: nginx-reverse-proxy
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-reverse-proxy
  type: ClusterIP
