apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3s-pv-2
spec:
  storageClassName: nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/clusterstorage/homebridge
    server: 192.168.4.66
    readOnly: false